# Flujo de trabajo simple para desplegar contenido estático a GitHub Pages
name: Desplegar DApp HTML a Pages

on:
  # Se ejecuta en los pushes dirigidos a la rama predeterminada
  push:
    branches: ["main", "principal"] # Asegúrate de que esto coincida con tu rama principal

  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña de Acciones
  workflow_dispatch:

# Establece los permisos de GITHUB_TOKEN para permitir el despliegue a GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente, saltándose las ejecuciones en cola entre la ejecución en curso y la última en cola.
# Sin embargo, NO canceles las ejecuciones en curso, ya que queremos permitir que estos despliegues de producción se completen.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Un único trabajo de despliegue, ya que solo estamos desplegando
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5
      - name: Subir artefacto de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # ¡IMPORTANTE! Especifica la carpeta 'app' donde está tu index.html
          path: './app' 
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
